apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: webhook
  name: webhook
spec:
  selector:
    matchLabels:
      app: webhook
  replicas: 2
  template:
    metadata:
      labels:
        app: webhook
    spec:
      containers:
      - image: kostiamol/webhook
        name: webhook
        ports:
        - containerPort: 80
          name: http
        command: ["webhook"]
    